// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4WnWH7nCZ-zdQhqPckzbvScZvPryvOk',
    appId: '1:779994331069:web:d31aad5a9deb85c9ddc4d4',
    messagingSenderId: '779994331069',
    projectId: 'engaztask-e5c04',
    authDomain: 'engaztask-e5c04.firebaseapp.com',
    storageBucket: 'engaztask-e5c04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdP0Lp-Q3n1GGyIZncwmqv5NPWc4wGpIg',
    appId: '1:779994331069:android:89cdd0dcd10249d1ddc4d4',
    messagingSenderId: '779994331069',
    projectId: 'engaztask-e5c04',
    storageBucket: 'engaztask-e5c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk9FYyLroZSeUSKuNgslrN4OqWWbbxCbE',
    appId: '1:779994331069:ios:aed20a5222323b59ddc4d4',
    messagingSenderId: '779994331069',
    projectId: 'engaztask-e5c04',
    storageBucket: 'engaztask-e5c04.appspot.com',
    iosClientId: '779994331069-9jjdmsk4ghq1ealefok4iqqj3vk0i3ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.engaztask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk9FYyLroZSeUSKuNgslrN4OqWWbbxCbE',
    appId: '1:779994331069:ios:aed20a5222323b59ddc4d4',
    messagingSenderId: '779994331069',
    projectId: 'engaztask-e5c04',
    storageBucket: 'engaztask-e5c04.appspot.com',
    iosClientId: '779994331069-9jjdmsk4ghq1ealefok4iqqj3vk0i3ot.apps.googleusercontent.com',
    iosBundleId: 'com.example.engaztask',
  );
}
